let arr=[11,14,21,31,44]
let amet=arr.toString()
console.log(typeof arr)
console.log(typeof amet)
let joinarr=arr.join("_")
// arr=arr.join("7")
console.log(arr)
console.log(amet)
console.log(joinarr)
let popele=arr.pop()
console.log(popele)
arr.push(50)
console.log(arr)
console.log(arr.length)
let r=arr.shift()
console.log(r)
console.log(arr.length)
console.log(arr)
let u=arr.unshift(5)
console.log(arr.join("_"))